accounts/urls.py
from django.urls import path
from .views import *
urlpatterns= [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register_view, name='register'),
  

]

challenges/urls.py
from django.urls import path, include
from .views import *
from rest_framework import routers

urlpatterns = [
     path('home/', HomePage, name="home"),
     path('about/', about_us, name='about'),
     path('appointments/', appointments, name='appointments'),
     path('services/',getServices, name='services'),
     path('contact/', getOptions, name="contact"),
     path('submit/', submitAppointment, name='submit_appointment'),
     path('appointment/<int:appointment_id>/update', update_appoitnment, name='update_appointment'),
]

monthly_challenges/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('challenges/', include('challenges.urls')),#Including urls for the CHALLENGES application
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    ]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)  #CSS, Javascript and Fonts
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  #Images

challenges/models.py
from django.db import models
from django.utils import timezone


# CUSTOMER Table...
class Customer(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField(unique=True)
    phone_number = models.CharField(max_length=20)
    address = models.CharField(max_length=200)
    # Add more fields as per your requirements
    def __str__(self):
        return self.first_name

# STAFF MEMBERS
class StaffMember(models.Model):
    POSITION_CHOICES = [
        ('cleaner', 'Custodian'),
        ('junior_beauty_technician', 'Junior Beauty Technician'),
        ('braiding_specialist', 'Braiding Specialist'),
         ('senior_hair_stylist', 'Senior Hair Stylist'),
        ('manager', 'Manager'),
    ]

    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField(unique=True)
    staff_image = models.ImageField(upload_to='staff/images', blank=True)
    phone_number = models.CharField(max_length=20)
    position = models.CharField(max_length=100, choices=POSITION_CHOICES)
    date_of_birth = models.DateField()
    # Add more fields as per your requirements

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

# Services offered by the salon
class Service(models.Model):
    STYLE_CHOICES = [
        ('bantu_knots', 'Bantu Knots'),
        ('box_braids', 'Box Braids'),
        ('feed_in_braids', 'Feed-in Braids'),
        ('tribal_braids', 'Tribal Braids'),
        ('passion_twists', 'Passion Twists'),
    ]
    name = models.CharField(max_length=100, choices=STYLE_CHOICES)
    description = models.TextField()
    price = models.DecimalField(max_digits=8, decimal_places=2)
    duration = models.IntegerField(help_text="Duration in minutes")
    image = models.ImageField(upload_to="img", default="img/chuenza.PNG")

    def __str__(self):
        return self.name
    
#Bookings Table
class Appointment(models.Model):
    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    booking_date = models.DateTimeField(default=timezone.now)
    scheduled_date = models.DateTimeField(null=True)

    def __str__(self):
        return f"{self.customer.first_name} - {self.service.name}"

challenges/forms.py
from .models import Appointment, Service
from django import forms

class updateAppointment(forms.ModelForm):
    class Meta:
        model = Appointment
        fields = ['service','customer','scheduled_date']

challenges/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseNotFound
from django.views import View
from .models import *
from rest_framework import viewsets, status
from rest_framework.exceptions import MethodNotAllowed
from rest_framework.response import Response
from rest_framework.decorators import api_view
from .serializers import BookSerializer
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect
from .forms import updateAppointment
from django.contrib import messages
from django.urls import reverse
from django.core.validators import validate_email
from django.core.exceptions import ValidationError


@login_required
def HomePage(request):
    return render(request,'index.html')

@login_required
def about_us(request):
    return render(request, 'about.html')

@login_required
def update_appoitnment(request, appointment_id):
    appointment = get_object_or_404(Appointment, pk=appointment_id) #First get the appointment

    if request.method == 'POST':
        form = updateAppointment(request.POST, instance=appointment)
        if form.is_valid():
            form.save()
            return redirect('appointments')
        else:
            messages.error(request, 'Enter correct Details')
            return redirect(reverse('update_appointment'))
        
    else:
        form = updateAppointment(instance=appointment)

    return render(request, 'update_appointment.html',{'form':form})

@login_required
def appointments(request):
    appointments = Appointment.objects.all()
    return render(request, 'appointments.html', {'appointments': appointments})

def getServices(request):
    services = Service.objects.all()
    return render(request, "services.html", {'services': services})

def submitAppointment(request):
   # services = Service.objects.values_list('name', flat=True) #flat=true returns a list instead of a turple
    services= Service.objects.all()
    if request.method == 'POST':
        names = request.POST['names']
        email = request.POST['email']
        hairstyle = request.POST['hairstyle']
        date_selected = request.POST['date']
        message = request.POST['message']

        if not names or not email or not hairstyle or not date_selected or not message:
            messages.error(request, "Please fill in all the fields")
        else:
            try:
                validate_email(email)
            except ValidationError:
                messages.error(request, "Please enter a valid email address")
            else:
                try:
                    service = services.get(name=hairstyle)
                except Service.DoesNotExist:
                    messages.error(request, "Invalid hairstyle selected.")
                else:
                    try:
                        customer = Customer.objects.get(email=email)
                    except Customer.DoesNotExist:
                        customer = Customer(first_name=names, email=email)
                        customer.save()
                    appointment = Appointment(service=service, customer=customer, scheduled_date = date_selected)
                    appointment.save()
                    messages.success(request, "Appointment created successfully!")
                    return redirect('contact')
        
    return redirect('contact')

def getOptions(request):
    services = Service.objects.all()
    return render(request, 'contact.html', {'services': services})

challenges/templates/about.html
{% extends 'base.html '%}
{%block content%}
<section class="hero">
  <h1>About Us</h1>
</section>

<section class="content">
  <h2>Welcome to Braids By Nkwane</h2>
  <p>
    We are a dedicated team of professionals committed to rendering the best salon management system in the industry. Our system is designed to streamline your salon operations, enhance customer experience, and boost your business productivity.
  </p>

  <h3>Our Mission</h3>
  <p>
    Our mission is to revolutionize the way salons manage their daily operations. We aim to provide a comprehensive solution that simplifies appointment scheduling, inventory management, employee tracking, and customer relationship management.
  </p>

  <h3>Why Choose Us?</h3>
  <ul>
    <li>Efficient and user-friendly software</li>
    <li>Customizable features to fit your salon's unique needs</li>
    <li>Real-time data analytics and reporting</li>
    <li>Dedicated customer support</li>
    <li>Continuous updates and improvements</li>
  </ul>

  <h3>Contact Us</h3>
  <p>
    If you have any questions or inquiries, feel free to reach out to us. We'd love to hear from you!
  </p>
  <p>
    Email: info@salonmanagementsystem.com<br>
    Phone: 123-456-7890
  </p>
</section>
{% endblock%}

challenges/templates/add_services.html
<div class="login-card">
  <div class="card-body">
    <h5 class="card-title">Add a New Service</h5>
    <form method="POST">
      {% csrf_token %}
      <div class="mb-3">
        <label for="username" class="form-label">Username</label>
        <input type="text" class="form-control" name="username">
      </div>
      <div class="mb-3">
        <label for="password" class="form-label">Password</label>
        <input class="form-control" type="password" name="password"></input>
      </div>
      <input type="submit" value="Submit" class="btn btn-info" />
    </form>
    <p class="mt-3">Don't have an account? Click <a href="{%url 'register'%}">here to sign up</a></p>
  </div>
</div>

challenges/templates/appointments.html
{% extends 'base.html' %}

{%block content %}

<!-- appointments.html -->

<section class="hero">
  <h1>Appointments</h1>
</section>
<!--<div class="d-flex justify-content-end">
  <a class="btn btn-primary ml-auto"> Add Appointment</a>
</div> --->
<div class="table-responsive mt-3">
  <table class="table table-striped table-info">
    <thead>
      <tr>
        <th>Customer Name</th>
        <th>Service</th>
        <th>Created Date</th>
        <th>Scheduled Date</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      {% for appointment in appointments %}
      <tr class="clickable-row"onclick="window.location='{% url 'update_appointment' appointment.id %}'">
        <td>{{ appointment.customer.first_name }} {{ appointment.customer.last_name }}</td>
        <td>{{ appointment.service.get_name_display }}</td>
        <td>{{ appointment.booking_date }}</td>
        <td>{{ appointment.scheduled_date }}</td>
        <td class="appointment_css"> <a class="btn btn-info"> Edit</a> <a class="btn btn-danger"> Delete</a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>


{% endblock %}

challenges/templates/base.html
<!DOCTYPE html>
<html>
<!--
superuser:
 >>>>> username: dashney22
 >>>>> password: @Dashney22

-->
{% load static %}
<head>
  <title>Salon Management System</title>
  <!-- Include your CSS and JavaScript files -->
 
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/dashboard.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/header.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/footer.css' %}">

  
</head>

<body>
  <!-- Include the header.html file -->
  {% include 'includes/header.html' %}

  <!-- Content specific to each template -->
  <div class="container mt-3">
    {% block content %}
    
    {% endblock %}
  </div>

  <!-- Include the footer.html file -->
  {% include 'includes/footer.html' %}

  <!-- Include your JavaScript files -->
 
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
    crossorigin="anonymous"></script>
  <!-- Option 2: Separate Popper and Bootstrap JS -->
   <!-- <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.7/dist/umd/popper.min.js" integrity="sha384-zYPOMqeu1DAVkHiLqWBUTcbYfZ8osu1Nd6Z89ify25QV9guujx43ITvfi12/QExE" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.min.js" integrity="sha384-Y4oOpwW3duJdCWv5ly8SCFYWqFDsfob/3GkgExXKV4idmbt98QcxXYs9UoXAB7BZ" crossorigin="anonymous"></script>
  -->
  </body>

</html>

challenges/templates/bookings.html
{% extends 'base.html'%}

{%block content%}
<section class="dashboard-title">
  <h1>Dashboard</h1>
</section>
  <div class="row">
    <!-- Top row -->
    <div class="col-md-4">
      <div class="card dashboard-card custom-1">
        <div class="card-body">
          <h5 class="card-title">Total Customers</h5>
          <p class="card-text">500</p>
        </div>
        <div class="card-footer">
          More info >
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="card dashboard-card custom-2">
        <div class="card-body">
          <h5 class="card-title">Accepted Appointments</h5>
          <p class="card-text">200</p>
        </div>
        <div class="card-footer">
          More info >
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="card dashboard-card custom-3">
        <div class="card-body">
          <h5 class="card-title">Rejected Appointments</h5>
          <p class="card-text">50</p>
        </div>
        <div class="card-footer">
          More info >
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <!-- Bottom row -->
    <div class="col-md-4">
      <div class="card dashboard-card custom-4">
        <div class="card-body">
          <h5 class="card-title">Total Sales</h5>
          <p class="card-text">$10,000</p>
        </div>
        <div class="card-footer">
          More info >
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="card dashboard-card custom-5">
        <div class="card-body">
          <h5 class="card-title">Yesterday's Sales</h5>
          <p class="card-text">$1,000</p>
        </div>
        <div class="card-footer">
          More info >
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="card dashboard-card custom-6">
        <div class="card-body">
          <h5 class="card-title">Last 7 Days Sales</h5>
          <p class="card-text">$5,000</p>
        </div>
        <div class="card-footer">
          More info >
        </div>
      </div>
    </div>
  </div>
{% endblock%}

challenges/templates/contact.html
{% extends 'base.html' %}

{%block content %}
<section>
  <div class="hero">
    <h4> Schedule an Appointment</h4>
  </div>
</section>
<section>
  {% if messages %}
  {% for message in messages %}
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    {{ message }}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
  {% endfor %}
  {% endif %}
</section>
<div class="appointment-card">
  <div class="card-body">
    <form method="post" action="{% url 'submit_appointment' %}">
      {% csrf_token %}
      <!-- Fields -->

      <div class="row">
        <div class="col-md-6">
          <div class="mb-3">
            <label for="names" class="form-label">Names</label>
            <input type="text" class="form-control" id="names" name="names">
          </div>
        </div>
        <div class="col-md-6">
          <div class="mb-3">
            <label for="email" class="form-label">Email</label>
            <input type="email" id="email" class="form-control" name="email">
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6">
          <div class="mb-3">
            <label for="hairstyle" class="form-label">Choose Hairstyle</label>
            <select id="hairstyle" name="hairstyle" class="form-control">
              {% for service in services %}
              <option value="{{ service.name }}">{{ service.get_name_display }}</option>
              {% endfor %}
            </select>
          </div>
        </div>
        <div class="col-md-6 mb-3">
          <label for="date" class="form-label">Select a Date</label>
          <input type="date" id="date" class="form-control" name="date">
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <div class="mb-2">
            <label for="message" class="form-label">Message</label>
            <textarea class="form-control" id="message" name="message" placeholder="Write to us"></textarea>
          </div>
        </div>
      </div>
      <input type="submit" value="Submit" class="btn btn-info" />
    </form>
  </div>
</div>

{% endblock %}

challenges/templates/index.html
{% extends 'base.html' %}

{%block content %}
<div class="landing-container mt-3">
  <div class="landing-text">
    <h1>Welcome to Braids By Nkwane </h1>
    <p>Managing your salon business with ease</p>
  </div>
</div>

{% endblock %}


<!--
  <div class="mt-1 mb-2">
    <h2><strong>Books List</strong> </h2>
  </div>


  <table class="table table-stripped table-dark">
    <tr>
      <th>
        Name
      </th>
      <th>
        Price
      </th>
      <th>
        Published
      </th>
    </tr>
    {% for book in books %}
    <tbody>
      <tr>
        <td> {{book.name}}</td>
        <td> R{{book.price}}</td>
        <td> {{book.is_published}}</td>
      </tr>
    </tbody>
    {% endfor %}
  </table> -->

challenges/templates/services.html
{% extends 'base.html' %}
{% load static %}
{%block content %}
<style>
  .card {
    border: 1px solid #ccc;
    border-radius: 4px;
    padding: 20px;
    margin-bottom: 20px;
  }

  .card img {
    width: 100%;
    height: 300px;
    object-fit: cover;
    /* Set a fixed height for the images */
    margin-bottom: 10px;
    /* Ensure images maintain their aspect ratio */
  }

  .card h5 {
    margin-top: 0;
  }

  .card p {
    margin-bottom: 10px;
  }
  .card .price{
    font-weight: bold;
    color: green;
  }
</style>

<div class="container">
  <section class="hero">
    <h1>Services</h1>
  </section>
  <div class="row">
    {% for service in services %}
    <div class="col-md-4">
      <div class="card rounded-4">
        <img src="{{ service.image.url }}" alt="{{ service.name }}">
        <h5>{{ service.get_name_display }}</h5>
        <p>{{ service.description }}</p>
        <p class="price">Price: R{{ service.price }}</p>
      </div>
    </div>
    {% endfor %}
  </div>

  <!-- Add another card here for the third row -->
</div>
{% endblock %}

challenges/templates/update_appointment.html
{% extends 'base.html' %}

{%block content %}

<div class="login-card">
  <div class="card-body">
    <h5 class="card-title">Update Appointment</h5>
    <form method="POST">
      {% csrf_token %}
      {{form.as_p}}
      <input type="submit" value="Submit" class="btn btn-info" />
    </form>
  </div>
</div>

{% endblock %}